---
default_language_version:
     python: python3.10
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
    - id: django-upgrade
      args: [--target-version, "3.1"]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
