---
default_language_version:
     python: python3.10
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.4.0
    hooks:
    - id: django-upgrade
      args: [--target-version, "3.1"]

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
