---
default_language_version:
     python: python3.9
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.3.2
    hooks:
    - id: django-upgrade
      args: [--target-version, "3.1"]

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
