---
default_language_version:
     python: python3.10
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.17.0
    hooks:
    - id: django-upgrade
      args: [--target-version, "3.1"]

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
