language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt --use-wheel
  - psql -c 'CREATE DATABASE ccbv' -U postgres
script: python manage.py test cbv
notifications:
  email: false
