[tool.black]
extend-exclude = '/(\.direnv|\.env|\.venv|venv)/'

[tool.isort]
default_section = "THIRDPARTY"
lines_after_imports = 2
profile = "black"
skip_glob = [".direnv", ".env", ".venv", "venv"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "inspector.settings"
python_files = [
  "test_*.py",
]
