[tool.black]
extend-exclude = '/(\.direnv|\.env|\.venv|venv)/'

[tool.isort]
default_section = "THIRDPARTY"
lines_after_imports = 2
profile = "black"
skip_glob = [".direnv", ".env", ".venv", "venv"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
many_errors_threshold = -1
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "inspector.settings"
python_files = [
  "test_*.py",
]
